### ISSUE TITLE
Can't save software configuration

### ISSUE THREAD

**Issue by dallen2018** [usnistgov/cds-tcamt#17]
On the validation screen I select the + next to Software List.  I set:
Name: SWP MDS
End Point: http://testws.swpartners.com/mdsservice/mds 
Connector Type: SWP MDS
and click the Save icon but the Name doesn't change in the Software List and the Play/Execute icon doesn't show up in the upper right above the test cases list.

**Comment by HossamT** [comment]
This should be solved, please let us now if you are still experiencing this issue.
