### ISSUE TITLE
Test Plan-level functionality

### ISSUE THREAD

**Issue by mindovina** [usnistgov/cds-tcamt#2]
Need a way to create Test Plans, and also clone them.

**Comment by mindovina** [comment]
..and delete them

**Comment by mindovina** [comment]
... and we need to be able to create Test Groups within a test plan (Test Groups contain Test Cases)

**Comment by HossamT** [comment]
Add Test Plan done

**Comment by HossamT** [comment]
Delete Test Plan done

**Comment by HossamT** [comment]
Open new issue for Groups
