### ISSUE TITLE
Export in CDC CDSi Spreadsheet format throwing "HTTP Status 500 – Internal Server Error"

### ISSUE THREAD

**Issue by jahartma** [usnistgov/cds-tcamt#22]
I am attempting to export the DTaP test cases (170 of them) in the CDC CDSi Spreadsheet format and cannot complete this export successfully.  I keep getting a "HTTP Status 500 – Internal Server Error".

**Comment by HossamT** [comment]
@jahartma thank you for reporting this issue, it has been solved and redeployed, please let us know if it's working as expected for you

**Comment by jahartma** [comment]
Thank you for the quick solution.  Everything appears to be working correctly.
